package dev.kuylar.freedit.api.models

import java.util.Date

class SubredditPost(
	val __typename: String,
	val createdAt: Date,
	val crosspostCount: Int,
	val isReactAlllowed: Boolean,
	val reactedFrom: Any?,
	val attributionInfo: Any?,
	val crowdControlLevel: String,
	val discussionType: String,
	val domain: String,
	val editedAt: Date?,
	val awardings: List<Any?>,
	val id: String,
	val isArchived: Boolean,
	val isCreatedFromAdsUi: Boolean,
	val isContestMode: Boolean,
	val isHidden: Boolean,
	val isLocked: Boolean,
	val isNsfw: Boolean,
	val isOriginalContent: Boolean,
	val isSaved: Boolean,
	val isScoreHidden: Boolean,
	val isSelfPost: Boolean,
	val isSpoiler: Boolean,
	val isStickied: Boolean,
	val isTrackingCrossposts: Boolean,
	val isVisited: Boolean,
	val liveCommentsWebsocket: String,
	val moderationInfo: Any?,
	val outboundLink: OutboundLink,
	val permalink: String,
	val removedBy: Any?,
	val removedByCategory: Any?,
	val topAwardedType: Any?,
	val score: Double?,
	val suggestedCommentSort: String,
	val title: String,
	val url: String,
	val whitelistStatus: String,
	val voteState: String,
	val authorFlair: Flair?,
	val authorInfo: TinyAuthor,
	val authorOnlyInfo: Any?,
	val commentCount: Double?,
	val content: TextContent,
	val distinguishedAs: Any?,
	val gallery: Gallery?,
	val isCrosspostable: Boolean,
	val isFollowed: Boolean,
	val isGildable: Boolean,
	val isMediaOnly: Boolean,
	val isPollIncluded: Boolean,
	val flair: Flair?,
	val media: PostMedia?,
	val postEventInfo: Any?,
	val thumbnail: Image,
	val upvoteRatio: Double,
	val viewCount: Double?,
	val poll: Any?,
	val subreddit: Subreddit?,
	val predictionTournament: Any?,
	val audioRoom: Any?,
	val crosspostRoot: Any?
) {
	fun isAd(): Boolean {
		return subreddit == null
	}
}
